#!/bin/sh

if [[ $# != 2 ]] ; then
  echo "Usage: $0 podName namespace"
  exit 1
fi 

PODS=$1
NAMESPACE=$2

NODE=$( kubectl describe pods $PODS -n $NAMESPACE  | grep -E "^Node" | awk -F'/' '{print $2}' )
POD_DESC=$( kubectl describe pods $PODS -n $NAMESPACE )
CONTAINERS=$( echo "$POD_DESC" | grep -E "Container ID" | awk -F'/' '{print $3}' )

CT_NUM=$(echo "$CONTAINERS" | wc -l )
CONTAINER=
if [[ $CT_NUM == 0 ]] ; then
  exit 0
elif [[ $CT_NUM == 1 ]] ; then
  CONTAINER="$CONTAINERS"
else 

  CONTAINERS_NAME=$( echo "$POD_DESC" | grep -B 1 -E "Container ID" | grep -E '^  [a-z]*:' | sed 's/://'  )
  echo "
Select:
$CONTAINERS_NAME
"
  read CT_NAME
  CONTAINER=$( echo "$POD_DESC" | grep -B 1 -E "Container ID" | grep -A 1 "$CT_NAME" | grep -v "$CT_NAME" | awk -F'/' '{print $3}' ) 

fi

ssh -t $NODE docker exec -ti $CONTAINER bash
